config/routes.rb
require './lib/api/base'

Rails.application.routes.draw do

  resources :visualizations
  resources :review_requests do
    collection do
      get 'report'
    end
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :user_abilities
  resources :contributors
  resources :invitees
  resources :databank_tasks, only: [:index, :show]
  get '/databank_tasks/pending', to: 'databank_tasks#pending'
  post '/databank_tasks/update_status', to: 'databank_tasks#update_status', defaults: {format: 'json'}
  resources :ingest_responses

  resources :nested_items

  get '/researcher_spotlights', to: 'featured_researchers#index'

  resources :featured_researchers do
    member do
      get 'preview'
    end
  end

  get "/illinois_experts", to: "illinois_experts#index", defaults: {format: "xml"}
  get "/illinois_experts/example", to: "illinois_experts#example", defaults: {format: "xml"}
  get "/illinois_experts/persons", to: "illinois_experts#persons", defaults: {format: "xml"}

  get '/data_curation_network', to: 'data_curation_network#index'
  get '/data_curation_network/accounts', to: 'data_curation_network#accounts'
  get '/data_curation_network/login', to: 'data_curation_network#login'
  get '/data_curation_network/register', to: 'data_curation_network#register'
  get '/data_curation_network/my_account', to: 'data_curation_network#my_account'
  get '/data_curation_network/datasets', to: 'data_curation_network#datasets'
  get '/data_curation_network/after_registration', to: 'data_curation_network#after_registration'
  get '/data_curation_network/account/add', to: 'data_curation_network#add_account'
  get '/data_curation_network/accounts/:id/edit', to: 'data_curation_network#edit_account'
  patch '/data_curation_network/identity/:id/update', to: 'data_curation_network#update_identity'

  get '/featured_researchers/:id', to: 'featured_researchers#show'

  get '/datasets/download_citation_report', to: 'datasets#download_citation_report'

  get '/datasets/:dataset_id/datafiles/add', to: 'datafiles#add'

  get '/datasets/:id/recordtext', to: 'datasets#recordtext'

  resources :tokens
  resources :admin
  get "/datasets/pre_deposit", to: "datasets#pre_deposit"

  get "/on_failed_registration", to: "welcome#on_failed_registration"

  resources :account_activations, only: [:edit]
  resources :related_materials
  resources :funders
  resources :definitions
  resources :medusa_ingests
  post "/medusa_ingests/remove_draft_if_in_medusa", to: "medusa_ingests#remove_draft_if_in_medusa"
  resources :datafiles
  resources :users
  resources :identities do
    collection do
      get 'register'
      get 'login'
    end
  end
  resources :datasets do

    member do
      post 'permissions', to: 'datasets#update_permissions'
    end

    resources :datafiles do
      member do
        get 'upload', to: 'datafiles#upload'
        patch 'upload', to: 'datafiles#do_upload'
        get 'resume_upload', to: 'datafiles#resume_upload'
        patch 'update_status', to: 'datafiles#update_status'
        get 'reset_upload', to: 'datafiles#reset_upload'
        get 'preview', to: 'datafiles#preview'
        get 'view', to: 'datafiles#view'
        get 'filepath', to: 'datafiles#filepath', defaults: {format: 'json'}
        get 'bucket_and_key', to: 'datafiles#bucket_and_key', defaults: {format: 'json'}
        get 'viewtext', to: 'datafiles#peek_text', defaults: {format: 'json'}
        get 'iiif_filepath', to: 'datafiles#iiif_filepath', defaults: {format: 'json'}
      end
    end
    resources :creators
    resources :funders
    resources :related_materials
  end
  resources :creators

  root 'welcome#index'

  get '/', to: 'welcome#index'

  get '/check_token', to: 'welcome#check_token'

  get '/restoration_events', to: 'restoration_events#index'

  get '/audits', to: 'admin#audits'

  get '/policies', to: 'policies#index', :as => :policies
  get '/help', to: 'help#index', :as => :help
  get '/welcome/deposit_login_modal', to: 'welcome#deposit_login_modal'
  get '/datasets/:id/download_endNote_XML', to: 'datasets#download_endNote_XML'
  get '/datasets/:id/download_BibTeX', to: 'datasets#download_BibTeX'
  get '/datasets/:id/download_RIS', to: 'datasets#download_RIS'
  get '/datasets/:id/download_plaintext_citation', to: 'datasets#download_plaintext_citation'
  get '/datasets/:id/download_plaintext_citation', to: 'datasets#download_plaintext_citation'
  get '/datasets/:id/download_box_file/:box_file_id', to: 'datasets#download_box_file'
  post '/datasets/:id/send_to_medusa', to: 'datasets#send_to_medusa', defaults: {format: 'json'}

  post 'api/dataset/:dataset_key/upload', to: 'api_dataset#upload', defaults: {format: 'json'}
  post 'api/dataset/:dataset_key/datafile', to: 'api_dataset#datafile', defaults: {format: 'json'}

  get '/datasets/:id/publish', to: 'datasets#publish'

  get '/datasets/:id/reserve_doi', to: 'datasets#reserve_doi', defaults: {format: 'json'}

  get '/datasets/:id/tombstone', to: 'datasets#tombstone'

  get '/datasets/:id/nuke', to: 'datasets#nuke'

  get '/review_deposit_agreement', to: 'datasets#review_deposit_agreement'
  get '/datasets/:id/review_deposit_agreement', to: 'datasets#review_deposit_agreement'

  get '/datasets/:id/get_new_token', to: 'datasets#get_new_token', defaults: {format: 'json'}

  get '/datasets/:id/get_current_token', to: 'datasets#get_current_token', defaults: {format: 'json'}

  get '/datasets/:id/add_review_request', to: 'dataset#add_review_request'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/login', to: 'sessions#new', as: :login, via: [:get, :post]
  match '/logout', to: 'sessions#destroy', as: :logout, via: [:get, :post]

  match '/auth/failure', to: 'sessions#unauthorized', as: :unauthorized, via: [:get, :post]

  get "/datafiles/:id/download", to: "datafiles#download"

  get "/datafiles/:id/download_no_record", to: "datafiles#download_no_record"

  get '/datafiles/:id/view', to: "datafiles#view"

  get '/datafiles/:id/filepath', to: "datafiles#filepath", defaults: {format: 'json'}

  get '/datafiles/:id/viewtext', to: 'datafiles#peek_text', defaults: {format: 'json'}

  get '/datafiles/:id/iiif_filepath', to: "datafiles#iiif_filepath", defaults: {format: 'json'}

  post "/datafiles/create_from_url", to: 'datafiles#create_from_url'

  get "/datasets/:id/datafiles/:web_id/cancel_box_upload", to: 'datasets#cancel_box_upload', defaults: {format: 'json'}

  get "/datasets/:id/citation_text", to: 'datasets#citation_text', defaults: {format: 'json'}

  post "/datafiles/remote_content_length", to: 'datafiles#remote_content_length', defaults: {format: 'json'}

  post "/datafiles/create_from_remote", to: 'datafiles#create_from_url_unknown_size', defaults: {format: 'json'}

  get "/datasets/:id/confirmation_message", to: 'datasets#confirmation_message', defaults: {format: 'json'}

  match "/datasets/:id/validate_change2published", to: 'datasets#validate_change2published', via: [:get, :post, :patch], defaults: {format: 'json'}

  post "/creators/update_row_order", to: 'creators#update_row_order'
  post "/creators/create_for_form", to: 'creators#create_for_form', defaults: {format: 'json'}

  post "/help/help_mail", to: 'help#help_mail', as: :help_mail

  post "/role_switch", to: 'sessions#role_switch'

  get "/datasets/:id/download_link", to: 'datasets#download_link', defaults: {format: 'json'}

  get "/datasets/:id/serialization", to: 'datasets#serialization', defaults: {format: 'json'}

  get "/datasets/:id/changelog", to: 'changelogs#edit'

  get "/metrics/dataset_downloads", to: 'metrics#dataset_downloads', defaults: {format: 'json'}

  get "/metrics/file_downloads", to: 'metrics#file_downloads', defaults: {format: 'json'}

  get "/metrics/datafiles_simple_list", to: "metrics#datafiles_simple_list"

  get "/metrics/datasets_csv", to: "metrics#datasets_csv"

  get "/metrics/funders_csv", to: "metrics#funders_csv"

  get "/metrics/datafiles_csv", to: "metrics#datafiles_csv"

  get "/metrics/related_materials_csv", to: "metrics#related_materials_csv"

  get "/metrics/archived_content_csv", to: "metrics#archived_content_csv"

  get "/metrics", to: 'metrics#index'

  get "/datasets/:id/download_metrics", to: 'datasets#download_metrics', defaults: {format: 'json'}

  get "/datasets/:id/request_review", to: 'datasets#request_review', defaults: {format: 'html'}

  get "/sitemap.xml", to: 'sitemaps#index', defaults: {format: 'xml'}

  get "/robots.:format", to: "welcome#robots"

  match "/*a" => "errors#error404", :constraints => lambda{|req| req.path !~/progress-job/ && req.path !~ /datatables/ }, via: [ :get, :post, :patch, :delete ]

end

app/views/admin/_form.html.haml
= form_for @admin do |f|
  - if @admin.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin.errors.count, "error")} prohibited this admin from being saved:"
      %ul
        - @admin.errors.full_messages.each do |msg|
          %li= msg

  .field
    .form-group
      = f.label :read_only_alert, class: "control-label", value: "Read Only Alert Custom Message Segment:"
      %br
      %ul
        %li A message saved here will be appended to the default alert message for file-only fallback mode.  This can be used to include instance-specific information, such as expected timeframe for resumption of normal operations.
        %li The alert message will only show on deposit-relevant pages when the system is in read-only fallback mode.
      = f.text_area :read_only_alert, id: "read-only-alert-text", class: "form-control", value: @admin.read_only_alert
  .actions
    .row
      .col-md-2.col-md-offset-10
        %button(type="submit" class="btn btn-block btn-primary" ) Update
        %button(type="button" class="btn btn-block btn-info" onclick="clear_alert_message()" ) Clear Form

      %p

%strong Current alert (before Update):
.alert.alert-alert
  Illinois Data Bank system is undergoing maintenance, and
  %strong datasets cannot currently be added or edited.
  -if Admin.instance.read_only_alert && Admin.instance.read_only_alert != ''
    %br
    =Admin.instance.read_only_alert
  %br
  Please
  %a(href="/help#contact" target="_blank")
    contact the Research Data Service Team
  with questions.

app/views/admin/audits.html.haml
=@audits.count

app/views/admin/edit.html.haml
= render 'form'

app/views/admin/index.html.haml
-if (can? :manage, @admin)
  =render partial: 'form'
-else
  .alert.alert-alert
    You are not authorized to access this page.


-#%h1 Listing admin
-#
-#%table
-#  %thead
-#    %tr
-#      %th Read only alert
-#      %th Singleton guard
-#      %th
-#      %th
-#      %th
-#
-#  %tbody
-#    - @admin.each do |admin|
-#      %tr
-#        %td= admin.read_only_alert
-#        %td= admin.singleton_guard
-#        %td= link_to 'Show', admin
-#        %td= link_to 'Edit', edit_admin_path(admin)
-#        %td= link_to 'Destroy', admin, :method => :delete, :data => { :confirm => 'Are you sure?' }
-#
-#%br
-#
-#= link_to 'New Admin', new_admin_path

app/views/admin/new.html.haml
%h1 New admin

= render 'form'

= link_to 'Back', admin_index_path

app/views/admin/show.html.haml
%p#notice= notice

%p
  %strong Read-only Alert Preview:
  .alert.alert-alert
    Illinois Data Bank system is undergoing maintenance, and
    %strong datasets cannot currently be added or edited.
    -if Admin.instance.read_only_alert && Admin.instance.read_only_alert != ''
      %br
      =Admin.instance.read_only_alert
    %br
    Please
    %a(href="/help#contact" target="_blank")
      contact the Research Data Service Team
    with questions.

.pull-right

  = link_to 'Edit', edit_admin_path(@admin), class: "idb btn btn-primary"