config/routes.rb
require './lib/api/base'

Rails.application.routes.draw do

  resources :visualizations
  resources :review_requests do
    collection do
      get 'report'
    end
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :user_abilities
  resources :contributors
  resources :invitees
  resources :databank_tasks, only: [:index, :show]
  get '/databank_tasks/pending', to: 'databank_tasks#pending'
  post '/databank_tasks/update_status', to: 'databank_tasks#update_status', defaults: {format: 'json'}
  resources :ingest_responses

  resources :nested_items

  get '/researcher_spotlights', to: 'featured_researchers#index'

  resources :featured_researchers do
    member do
      get 'preview'
    end
  end

  get "/illinois_experts", to: "illinois_experts#index", defaults: {format: "xml"}
  get "/illinois_experts/example", to: "illinois_experts#example", defaults: {format: "xml"}
  get "/illinois_experts/persons", to: "illinois_experts#persons", defaults: {format: "xml"}

  get '/data_curation_network', to: 'data_curation_network#index'
  get '/data_curation_network/accounts', to: 'data_curation_network#accounts'
  get '/data_curation_network/login', to: 'data_curation_network#login'
  get '/data_curation_network/register', to: 'data_curation_network#register'
  get '/data_curation_network/my_account', to: 'data_curation_network#my_account'
  get '/data_curation_network/datasets', to: 'data_curation_network#datasets'
  get '/data_curation_network/after_registration', to: 'data_curation_network#after_registration'
  get '/data_curation_network/account/add', to: 'data_curation_network#add_account'
  get '/data_curation_network/accounts/:id/edit', to: 'data_curation_network#edit_account'
  patch '/data_curation_network/identity/:id/update', to: 'data_curation_network#update_identity'

  get '/featured_researchers/:id', to: 'featured_researchers#show'

  get '/datasets/download_citation_report', to: 'datasets#download_citation_report'

  get '/datasets/:dataset_id/datafiles/add', to: 'datafiles#add'

  get '/datasets/:id/recordtext', to: 'datasets#recordtext'

  resources :tokens
  resources :admin
  get "/datasets/pre_deposit", to: "datasets#pre_deposit"

  get "/on_failed_registration", to: "welcome#on_failed_registration"

  resources :account_activations, only: [:edit]
  resources :related_materials
  resources :funders
  resources :definitions
  resources :medusa_ingests
  post "/medusa_ingests/remove_draft_if_in_medusa", to: "medusa_ingests#remove_draft_if_in_medusa"
  resources :datafiles
  resources :users
  resources :identities do
    collection do
      get 'register'
      get 'login'
    end
  end
  resources :datasets do

    member do
      post 'permissions', to: 'datasets#update_permissions'
    end

    resources :datafiles do
      member do
        get 'upload', to: 'datafiles#upload'
        patch 'upload', to: 'datafiles#do_upload'
        get 'resume_upload', to: 'datafiles#resume_upload'
        patch 'update_status', to: 'datafiles#update_status'
        get 'reset_upload', to: 'datafiles#reset_upload'
        get 'preview', to: 'datafiles#preview'
        get 'view', to: 'datafiles#view'
        get 'filepath', to: 'datafiles#filepath', defaults: {format: 'json'}
        get 'bucket_and_key', to: 'datafiles#bucket_and_key', defaults: {format: 'json'}
        get 'viewtext', to: 'datafiles#peek_text', defaults: {format: 'json'}
        get 'iiif_filepath', to: 'datafiles#iiif_filepath', defaults: {format: 'json'}
      end
    end
    resources :creators
    resources :funders
    resources :related_materials
  end
  resources :creators

  root 'welcome#index'

  get '/', to: 'welcome#index'

  get '/check_token', to: 'welcome#check_token'

  get '/restoration_events', to: 'restoration_events#index'

  get '/audits', to: 'admin#audits'

  get '/policies', to: 'policies#index', :as => :policies
  get '/help', to: 'help#index', :as => :help
  get '/welcome/deposit_login_modal', to: 'welcome#deposit_login_modal'
  get '/datasets/:id/download_endNote_XML', to: 'datasets#download_endNote_XML'
  get '/datasets/:id/download_BibTeX', to: 'datasets#download_BibTeX'
  get '/datasets/:id/download_RIS', to: 'datasets#download_RIS'
  get '/datasets/:id/download_plaintext_citation', to: 'datasets#download_plaintext_citation'
  get '/datasets/:id/download_plaintext_citation', to: 'datasets#download_plaintext_citation'
  get '/datasets/:id/download_box_file/:box_file_id', to: 'datasets#download_box_file'
  post '/datasets/:id/send_to_medusa', to: 'datasets#send_to_medusa', defaults: {format: 'json'}

  post 'api/dataset/:dataset_key/upload', to: 'api_dataset#upload', defaults: {format: 'json'}
  post 'api/dataset/:dataset_key/datafile', to: 'api_dataset#datafile', defaults: {format: 'json'}

  get '/datasets/:id/publish', to: 'datasets#publish'

  get '/datasets/:id/reserve_doi', to: 'datasets#reserve_doi', defaults: {format: 'json'}

  get '/datasets/:id/tombstone', to: 'datasets#tombstone'

  get '/datasets/:id/nuke', to: 'datasets#nuke'

  get '/review_deposit_agreement', to: 'datasets#review_deposit_agreement'
  get '/datasets/:id/review_deposit_agreement', to: 'datasets#review_deposit_agreement'

  get '/datasets/:id/get_new_token', to: 'datasets#get_new_token', defaults: {format: 'json'}

  get '/datasets/:id/get_current_token', to: 'datasets#get_current_token', defaults: {format: 'json'}

  get '/datasets/:id/add_review_request', to: 'dataset#add_review_request'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/login', to: 'sessions#new', as: :login, via: [:get, :post]
  match '/logout', to: 'sessions#destroy', as: :logout, via: [:get, :post]

  match '/auth/failure', to: 'sessions#unauthorized', as: :unauthorized, via: [:get, :post]

  get "/datafiles/:id/download", to: "datafiles#download"

  get "/datafiles/:id/download_no_record", to: "datafiles#download_no_record"

  get '/datafiles/:id/view', to: "datafiles#view"

  get '/datafiles/:id/filepath', to: "datafiles#filepath", defaults: {format: 'json'}

  get '/datafiles/:id/viewtext', to: 'datafiles#peek_text', defaults: {format: 'json'}

  get '/datafiles/:id/iiif_filepath', to: "datafiles#iiif_filepath", defaults: {format: 'json'}

  post "/datafiles/create_from_url", to: 'datafiles#create_from_url'

  get "/datasets/:id/datafiles/:web_id/cancel_box_upload", to: 'datasets#cancel_box_upload', defaults: {format: 'json'}

  get "/datasets/:id/citation_text", to: 'datasets#citation_text', defaults: {format: 'json'}

  post "/datafiles/remote_content_length", to: 'datafiles#remote_content_length', defaults: {format: 'json'}

  post "/datafiles/create_from_remote", to: 'datafiles#create_from_url_unknown_size', defaults: {format: 'json'}

  get "/datasets/:id/confirmation_message", to: 'datasets#confirmation_message', defaults: {format: 'json'}

  match "/datasets/:id/validate_change2published", to: 'datasets#validate_change2published', via: [:get, :post, :patch], defaults: {format: 'json'}

  post "/creators/update_row_order", to: 'creators#update_row_order'
  post "/creators/create_for_form", to: 'creators#create_for_form', defaults: {format: 'json'}

  post "/help/help_mail", to: 'help#help_mail', as: :help_mail

  post "/role_switch", to: 'sessions#role_switch'

  get "/datasets/:id/download_link", to: 'datasets#download_link', defaults: {format: 'json'}

  get "/datasets/:id/serialization", to: 'datasets#serialization', defaults: {format: 'json'}

  get "/datasets/:id/changelog", to: 'changelogs#edit'

  get "/metrics/dataset_downloads", to: 'metrics#dataset_downloads', defaults: {format: 'json'}

  get "/metrics/file_downloads", to: 'metrics#file_downloads', defaults: {format: 'json'}

  get "/metrics/datafiles_simple_list", to: "metrics#datafiles_simple_list"

  get "/metrics/datasets_csv", to: "metrics#datasets_csv"

  get "/metrics/funders_csv", to: "metrics#funders_csv"

  get "/metrics/datafiles_csv", to: "metrics#datafiles_csv"

  get "/metrics/related_materials_csv", to: "metrics#related_materials_csv"

  get "/metrics/archived_content_csv", to: "metrics#archived_content_csv"

  get "/metrics", to: 'metrics#index'

  get "/datasets/:id/download_metrics", to: 'datasets#download_metrics', defaults: {format: 'json'}

  get "/datasets/:id/request_review", to: 'datasets#request_review', defaults: {format: 'html'}

  get "/sitemap.xml", to: 'sitemaps#index', defaults: {format: 'xml'}

  get "/robots.:format", to: "welcome#robots"

  match "/*a" => "errors#error404", :constraints => lambda{|req| req.path !~/progress-job/ && req.path !~ /datatables/ }, via: [ :get, :post, :patch, :delete ]

end

app/models/featured_researcher.rb
class FeaturedResearcher < ActiveRecord::Base
end

app/controllers/featured_researchers_controller.rb
class FeaturedResearchersController < ApplicationController

  authorize_resource
  skip_load_and_authorize_resource :only => [:show, :index]
  before_action :set_featured_researcher, only: [:show, :preview, :edit, :update, :destroy]

  # GET /featured_researchers
  # GET /featured_researchers.json
  def index

    if current_user && current_user.role && current_user.role == "admin"
      @featured_researchers = FeaturedResearcher.all
    else
      active_featured_researchers = FeaturedResearcher.where(is_active: true)
      @featured_researchers = active_featured_researchers.order("RANDOM()")
    end

  end

  # GET /featured_researchers/1
  # GET /featured_researchers/1.json
  def show
  end

  def preview
  end

  # GET /featured_researchers/new
  def new
    @featured_researcher = FeaturedResearcher.new
  end

  # GET /featured_researchers/1/edit
  def edit
  end

  # POST /featured_researchers
  # POST /featured_researchers.json
  def create
    @featured_researcher = FeaturedResearcher.new(featured_researcher_params)

    respond_to do |format|
      if @featured_researcher.save
        format.html { render :preview }
        format.json { render json: to_fileupload, content_type: request.format, :layout => false }
      else
        format.html { render :new }
        format.json { render json: @featured_researcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /featured_researchers/1
  # PATCH/PUT /featured_researchers/1.json
  def update
    respond_to do |format|
      if @featured_researcher.update(featured_researcher_params)
        format.html { render :preview }
        format.json { render json: to_fileupload, content_type: request.format, :layout => false }
      else
        format.html { render :edit }
        format.json { render json: @featured_researcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /featured_researchers/1
  # DELETE /featured_researchers/1.json
  def destroy
    @featured_researcher.destroy
    respond_to do |format|
      format.html { redirect_to featured_researchers_url, notice: 'Featured researcher entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_featured_researcher
      @featured_researcher = FeaturedResearcher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def featured_researcher_params
      params.require(:featured_researcher).permit(:name, :question, :dataset_url, :article_url, :bio, :testimonial, :photo_url, :is_active)
    end

    def to_fileupload
      {
          files:
              [
                  {
                      featureid: @featured_researcher.id,
                      image_url: @featured_researcher.binary_url,
                      url: featured_researcher_url,
                      delete_url: featured_researchers_url,
                      delete_type: "DELETE",
                      name: "#{@featured_researcher.binary.file.filename}",
                      size: "#{number_to_human_size(@featured_researcher.binary.size)}"
                  }
              ]
      }

    end
end

app/helpers/featured_researchers_helper.rb
module FeaturedResearchersHelper
end

app/views/featured_researchers/_form.html.haml
= form_for @featured_researcher do |f|
  - if @featured_researcher.errors.any?
    #error_explanation
      %h2= "#{pluralize(@featured_researcher.errors.count, "error")} prohibited this featured researcher record from being saved:"
      %ul
        - @featured_researcher.errors.full_messages.each do |msg|
          %li= msg

  =f.hidden_field :is_active, value: @featured_researcher.is_active | false

  .form-group.row
    .field
      = f.label :photo_url, "Photo URL", class: "control-label"
      = f.text_field :photo_url, class: "form-control"

  -if @featured_researcher.photo_url && @featured_researcher.photo_url != ""
    .row
      .col-md-5
        .photo-preview
          %img(src="#{@featured_researcher.photo_url}" class="img-responsive" alt="featured researcher photo" )

  .form-group.row
    .field
      = f.label :name, "Name Line", class: "control-label"
      = f.text_field :name, class: "form-control"

  .form-group.row
    .field
      = f.label :bio, "Biography", class: "control-label"
      = f.text_area :bio, class: "form-control"

  .form-group.row
    .field
      = f.label :dataset_url, "Dataset URL", class: "control-label"
      = f.text_field :dataset_url, class: "form-control"

  .form-group.row
    .field
      = f.label :article_url, "Article URL", class: "control-label"
      = f.text_field :article_url, class: "form-control"

  .form-group.row
    .field
      = f.label :question, "Testimonial Prompt", class: "control-label"
      = f.text_field :question, class: "form-control"

  .form-group.row
    .field
      = f.label :testimonial, "Testimonial", class: "control-label"
      = f.text_area :testimonial, class: "form-control"

  .row
    .col-md-2.col-md-offset-10
      = f.submit 'Save and Preview', class: "btn btn-primary btn-block"

app/views/featured_researchers/_individual.html.haml
.row
  .col-md-2
    -if featured_researcher.photo_url && featured_researcher.photo_url != ""
      .photo-preview
        %img(src="#{featured_researcher.photo_url}" class="img-responsive featured-img" alt="featured researcher photo" )
    -else
      .no-image-available
        No photo available.

  .col-md-6
    %h4
      %strong
        =link_to featured_researcher.name, featured_researcher_path(featured_researcher)
    = featured_researcher.bio.html_safe

    .featured-comment

      .more-elbow
        %strong
          = featured_researcher.question
      .elbow
        = featured_researcher.testimonial.html_safe

  .col-md-2
    -if featured_researcher.dataset_url && featured_researcher.dataset_url != ''
      %button(type="button" class="btn btn-primary btn-block" onclick="window.open('#{featured_researcher.dataset_url}')" )
        %span(class="glyphicon glyphicon-tasks" )
        &nbsp;
        dataset
    -if featured_researcher.article_url && featured_researcher.article_url != ''
      %button(type="button" class="btn btn-primary btn-block" onclick="window.open('#{featured_researcher.article_url}')" )
        %span(class="glyphicon glyphicon-file" )
        &nbsp;
        article
  .col-md-2
    -if(can? :manage, featured_researcher)
      .curator-only
        -if featured_researcher.is_active
          .label.label-default
            Published
        -else
          .label.label-default
            Not Published


        = form_for featured_researcher do |f|

          =f.hidden_field :name, value: featured_researcher.name
          =f.hidden_field :question, value: featured_researcher.question
          =f.hidden_field :dataset_url, value: featured_researcher.dataset_url
          =f.hidden_field :article_url, value: featured_researcher.article_url
          =f.hidden_field :bio, value: featured_researcher.bio
          =f.hidden_field :testimonial, value: featured_researcher.testimonial
          =f.hidden_field :photo_url, value: featured_researcher.photo_url


          -if featured_researcher.is_active
            =f.hidden_field :is_active, value: false
            = f.submit 'Unpublish', class: "btn btn-warning btn-block elbow"
          -else
            =f.hidden_field :is_active, value: true
            = f.submit 'Publish', class: "btn btn-warning btn-block elbow"

        %a(href="/featured_researchers/#{featured_researcher.id}/preview" class="btn btn-primary btn-block idb elbow") Preview
        %a(href="/featured_researchers/#{featured_researcher.id}/edit" class="btn btn-success btn-block idb" ) Edit
        =link_to '<button class="btn btn-danger btn-block idb elbow ">Delete</button>'.html_safe, featured_researcher, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/featured_researchers/edit.html.haml
.container-fluid

  = render 'form'
  .row
    .col-md-2.col-md-offset-10
      =link_to '<button class="btn btn-danger btn-block idb elbow ">Delete</button>'.html_safe, @featured_researcher, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/featured_researchers/index.html.haml
.container-fluid
  %h1 Researcher Spotlights
  %hr

  -if @featured_researchers

    - @featured_researchers.each do |featured_researcher|
      = render 'individual', featured_researcher:featured_researcher
      %hr

-if(can? :manage, FeaturedResearcher)
  .container-fluid
    .row
      .col-md-3.col-md-offset-9.curator-only
        = link_to 'New Featured researcher', new_featured_researcher_path, class: "btn btn-primary btn-block idb"

app/views/featured_researchers/new.html.haml
%h1 New Featured Researcher
.container-fluid
  = render 'form'

= link_to 'Back', featured_researchers_path

app/views/featured_researchers/preview.html.haml
.container-fluid
  .welcome
    .row
      .col-md-8
        %h3 You are ready to deposit data if:
        %ul
          %li your data is in a final state and not expected to undergo revisions.
          %li you have removed any private, confidential, or other legally protected information from your data.
          %li you are a faculty member, staff member, or graduate student at the University of Illinois at Urbana-Champaign.
          %li you have permission to publicly distribute data from all creator(s) and/or copyright owner(s).

        %h3 Published data:
        %ul
          %li is open to anyone in the world.
          %li
            =surround('receives a stable identifier (',  ') for easy reference and citation.') do
              %a{href: "/help#doi", target: "_blank"} DOI
          %li is readily available for anyone to access for a minimum of 5 years.
          %li is located in a stable environment that complies with many funder and publisher requirements.
        %button(type="button" class="btn btn-default" onclick="window.open('/help#start')" )
          Learn how to publish your data
        %h3 Statement of Commitment
        .indent
          %p The Illinois Data Bank's mission is to centralize, preserve, and provide persistent and reliable access to the research data created by affiliates of the University of Illinois at Urbana-Champaign, such as its faculty, academic staff, and graduate students. The Research Data Service at the University Library maintains and operates the Illinois Data Bank on behalf of the University of Illinois at Urbana-Champaign campus.  The University Library has a long history of successfully supporting the preservation of and access to Illinois research outputs. The Illinois Data Bank operates within a robust policy framework that fully describes the University's commitment to providing persistent and reliable access to research data.
        %button(type="button" class="btn btn-default" onclick="window.open('/policies')" )
          Review our policies
      .col-md-4.featured-researcher
        %h3 Researcher Spotlight
        .featured-bio
          -if @featured_researcher.photo_url && @featured_researcher.photo_url != ""
            .photo-preview
              %img(src="#{@featured_researcher.photo_url}" class="img-responsive" alt="featured researcher photo" )

          %h4
            %strong
              = @featured_researcher.name
          = @featured_researcher.bio.html_safe

        .featured-buttons
          -if @featured_researcher.dataset_url && @featured_researcher.dataset_url != ''
            %button(type="button" class="btn btn-primary btn-block" onclick="window.open('#{@featured_researcher.dataset_url}')" )
              %span(class="glyphicon glyphicon-tasks" )
              &nbsp;
              dataset
          -if @featured_researcher.article_url && @featured_researcher.article_url != ''
            %button(type="button" class="btn btn-primary btn-block" onclick="window.open('#{@featured_researcher.article_url}')" )
              %span(class="glyphicon glyphicon-file" )
              &nbsp;
              article

        .featured-comment
          %strong
            = @featured_researcher.question
          .elbow
            = @featured_researcher.testimonial.html_safe
        %hr

        = form_for @featured_researcher do |f|

          =f.hidden_field :name, value: @featured_researcher.name
          =f.hidden_field :question, value: @featured_researcher.question
          =f.hidden_field :dataset_url, value: @featured_researcher.dataset_url
          =f.hidden_field :article_url, value: @featured_researcher.article_url
          =f.hidden_field :bio, value: @featured_researcher.bio
          =f.hidden_field :testimonial, value: @featured_researcher.testimonial
          =f.hidden_field :photo_url, value: @featured_researcher.photo_url


          -if @featured_researcher.is_active
            =f.hidden_field :is_active, value: false
            = f.submit 'Unpublish', class: "btn btn-primary btn-block"
          -else
            =f.hidden_field :is_active, value: true
            = f.submit 'Publish', class: "btn btn-primary btn-block"

        .featured-controls
          %a(href="/featured_researchers/#{@featured_researcher.id}/edit" class="btn btn-success btn-block idb") Edit Researcher Spotlight
          %a(href="/featured_researchers"  class="btn btn-info btn-block idb" ) List Researcher Spotlights

app/views/featured_researchers/show.html.haml
.row
  .col-md-10.col-md-offset-2
    %h3 Researcher Spotlight
= render 'individual', featured_researcher: @featured_researcher